In [7]:
import numpy as np
a1 = np.array([1,2,3])

In [2]:
a2 = np.array([[1,2.0,3],[4,5,6.0]])
a3 = np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    [[10,11.0,12],
    [13,14,15],
    [16,17,18]]
])
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [18]:
type(a1),type(a2),type(a3)
a1.dtype
a4 = np.array(a2 * 2)
a4 = a3 *2 
a4
import pandas as pd
pd.DataFrame(a2)

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [32]:
np.random.seed(0)
a5 = np.random.randint(1,15,size=(5,3))
a5

array([[13,  6,  1],
       [ 4, 12,  4],
       [ 8, 10,  4],
       [ 6,  3,  5],
       [ 8,  7,  9]])

In [35]:
a6 = np.random.random(size=(5,4))
a6


array([[0.31542835, 0.36371077, 0.57019677, 0.43860151],
       [0.98837384, 0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959, 0.13818295],
       [0.19658236, 0.36872517, 0.82099323, 0.09710128]])

In [36]:
a7 = np.arange(0,20,1)
a7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
a8 = np.zeros((4,2))
a8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
a11 = np.random.randint(1,9,size=(2,3,4,5))
a11

array([[[[3, 5, 3, 1, 6],
         [4, 3, 3, 6, 1],
         [8, 6, 2, 8, 1],
         [3, 3, 4, 3, 8]],

        [[8, 4, 3, 2, 3],
         [7, 4, 7, 4, 4],
         [3, 7, 4, 5, 2],
         [3, 4, 7, 2, 3]],

        [[2, 5, 3, 7, 4],
         [1, 4, 3, 4, 1],
         [1, 7, 1, 7, 4],
         [7, 3, 4, 1, 5]]],


       [[[1, 6, 7, 1, 6],
         [3, 4, 7, 3, 4],
         [6, 1, 1, 1, 4],
         [8, 1, 3, 3, 1]],

        [[5, 4, 5, 6, 7],
         [1, 5, 4, 6, 4],
         [5, 7, 6, 2, 6],
         [4, 1, 1, 1, 6]],

        [[6, 7, 2, 1, 5],
         [2, 7, 6, 6, 4],
         [2, 1, 1, 5, 4],
         [4, 2, 7, 6, 8]]]])

In [62]:
a11[:,:,:,:1]

array([[[[3],
         [4],
         [8],
         [3]],

        [[8],
         [7],
         [3],
         [3]],

        [[2],
         [1],
         [1],
         [7]]],


       [[[1],
         [3],
         [6],
         [8]],

        [[5],
         [1],
         [5],
         [4]],

        [[6],
         [2],
         [2],
         [4]]]])

In [65]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(2,3))
mat2 = np.random.randint(10,size=(2,3,3))
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9]]),
 array([[[3, 5, 2],
         [4, 7, 6],
         [8, 8, 1]],
 
        [[6, 7, 7],
         [8, 1, 5],
         [9, 8, 9]]]))

In [68]:
mat1 = mat1.reshape(2,3,1)
mat1

array([[[5],
        [0],
        [3]],

       [[3],
        [7],
        [9]]])

In [69]:
mat1*mat2

array([[[15, 25, 10],
        [ 0,  0,  0],
        [24, 24,  3]],

       [[18, 21, 21],
        [56,  7, 35],
        [81, 72, 81]]])

In [71]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [73]:
np.dot(mat1,mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [74]:
np.random.seed(0)
weekly_report = np.random.randint(20,size=(5,3))
weekly_report

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [143]:
weekly_reports = pd.DataFrame(weekly_report,index=["Mon","Tues","Wed","Thur","Fri"],columns=["Alomond","Peanut","Cashew"])
weekly_reports

Alomond  Peanut  Cashew
Mon        12      15       0
Tues        3       3       7
Wed         9      19      18
Thur        4       6      12
Fri         1       6       7

In [134]:
Price = np.array([12,8,14])
Price

array([12,  8, 14])

In [132]:
Prices = pd.DataFrame(Price.reshape(1,3),index=["Price"],columns=["Alamond","Peanut","Cashew"])
Prices

Alamond  Peanut  Cashew
Price       12       8      14

In [144]:

weekly_reports["Total (RS)"] =  weekly_reports.dot(Price.T)
weekly_reports

Alomond  Peanut  Cashew  Total (RS)
Mon        12      15       0         264
Tues        3       3       7         158
Wed         9      19      18         512
Thur        4       6      12         264
Fri         1       6       7         158

In [155]:
from matplotlib.image import imread
panda = imread('images/panda.png')
panda.mean(),panda.std(),panda.var(),panda.size
panda[:10]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0